# Generated by Django 4.2.1 on 2023-06-08 10:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.IntegerField(choices=[(1, 'Urodziny'), (2, 'Wieczor kawalerski'), (3, 'Wieczor panienski'), (4, 'Wesele'), (5, 'Chrzciny'), (6, 'Komunia'), (7, 'Stodniowka'), (8, 'Jubileusz'), (9, 'Sylwester')])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('term', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_people', models.PositiveIntegerField()),
                ('accessories', models.ManyToManyField(to='events.accessories')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.category')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.client')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcontractor_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subcontractor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.subcontractor')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Oczekujące', 'Oczekujące'), ('Zaakceptowane', 'Zaakceptowane'), ('Odrzucone', 'Odrzucone')], default='Oczekujące', max_length=20)),
                ('ccreation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('subcontractor_services', models.ManyToManyField(to='events.subcontractor_service')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.place'),
        ),
    ]
