# Generated by Django 4.2.1 on 2023-06-08 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='price',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='ccreation_date',
        ),
        migrations.RemoveField(
            model_name='subcontractor_service',
            name='price',
        ),
        migrations.AddField(
            model_name='accessories',
            name='price_fixed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accessories',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='oferta',
            name='accessories',
            field=models.ManyToManyField(to='events.accessories'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='subcontractor_service',
            name='price_fixed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subcontractor_service',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='status',
            field=models.CharField(choices=[('Oczekujące', 'Oczekujące'), ('Zatwierdzone', 'Zatwierdzone'), ('Anulowane', 'Anulowane')], default='Oczekujące', max_length=20),
        ),
    ]
